### ISSUE TITLE
Running `php artisan ui vue --auth` on existing project

### ISSUE THREAD

**Issue by akupaka** [laravel/ui#101]
Hi there!

I am new to Laravel and while I was learning an online course I created new Laravel project with Composer.

Later on I was looking for a way to generate OOTB auth controllers etc.
Reading the docs led to to an idea to run `php artisan ui vue --auth`...

As you may already guessed that was a bad idea =)

Luckily I was using git so it was easy to recover js/app.js and other files. But other students might be not as experienced and could loose a part of their work.

So, if it is not so hard to implement it would be I nice feature to be warned that project files are being overwritten during this command.

Thank you!

**Comment by akupaka** [comment]
Oh! Also It would be a nice feature to be able to only generate Auth controllers =)

Thx!

**Comment by SvenjaJeschke** [comment]
Why is this closed? This would be an extremely important feature.
