### ISSUE TITLE
[2.x] Bootstrap stubs

### ISSUE THREAD

**Issue by mrcat323** [laravel/ui#106]
- UI Version: 2.0.3
- Laravel Version: 7.11.0
- PHP Version: 7.3.18
- Database Driver & Version:

### Description:
After creating a Laravel project, in js directory we have app.js and bootstrap.js.
![image](https://user-images.githubusercontent.com/23054662/83644701-ffb12e00-a5ca-11ea-9d48-340b1b924d9c.png)
What happens after ```artisan ui react```
![image](https://user-images.githubusercontent.com/23054662/83644967-53bc1280-a5cb-11ea-8320-7564cb77a9eb.png)
![image](https://user-images.githubusercontent.com/23054662/83645155-9382fa00-a5cb-11ea-8eea-aace41699e59.png)

We got *components* directory and some *Example.js* React component
When I did ```artisan ui vue```
We have the same folder structure here
![image](https://user-images.githubusercontent.com/23054662/83648705-cdee9600-a5cf-11ea-8f13-32a28e6af84b.png)

We got the same *components* directory but with a Vuejs file
![image](https://user-images.githubusercontent.com/23054662/83648638-b7483f00-a5cf-11ea-8274-b138a595f396.png)
But when I do ```artisan ui bootstrap```
Nothing changes...
![image](https://user-images.githubusercontent.com/23054662/83648705-cdee9600-a5cf-11ea-8f13-32a28e6af84b.png)
![image](https://user-images.githubusercontent.com/23054662/83648638-b7483f00-a5cf-11ea-8274-b138a595f396.png)
I mean it's bug some of that kind.
### Steps To Reproduce:
I'll be happy to contribute for fixing this "bug". **But I need to add one more file to *bootstrap-stub directory*, app.js file, with simple one-line code which requires *bootstrap.js* because after playing with ui presets I realized that after changing preset from vue, for example, to bootstrap, the file's content doesn't change, so that's why I thought it would be nice to add one more file**
What we have after switching back to `bootstrap` from `vue`
![image](https://user-images.githubusercontent.com/23054662/83650023-502b8a00-a5d1-11ea-8639-703148275a32.png)
The same is with `React`
![image](https://user-images.githubusercontent.com/23054662/83650145-73563980-a5d1-11ea-90a2-a8f63fda60bf.png)
**PR gonna be soon**

**Comment by driesvints** [comment]
You usually don't change presets like this. You choose the one you need and use that.
