### ISSUE TITLE
Creating an account does not regenerate session id

### ISSUE THREAD

**Issue by snjkg** [laravel/ui#108]
When logging in, the code calls $request->session()->regenerate(); which regenerates a new session.

However, when creating an account, this is no equivalent call meaning if a previously logged in user creates a new account (without logging out), it logs in, but the session data from the previously logged in user is still there.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by snjkg** [comment]
I dont understand, this is a defect not a question.

As per the Laravel documentation, the [session is regenerate on login](https://laravel.com/docs/7.x/session#regenerating-the-session-id) to avoid a session fixation attack. If you don't do it on creation, it would be subject to the same attack.

**Comment by driesvints** [comment]
The `RegisterController` has a guest middleware which requires you to logout first before registering again. If you modified this behavior you're also responsible for invalidating the previous session.

https://github.com/laravel/ui/blob/2.x/stubs/Auth/RegisterController.stub#L41

**Comment by snjkg** [comment]
Oh, I see what you mean. Thank you.
