### ISSUE TITLE
Create separate package for Auth

### ISSUE THREAD

**Issue by shahvirag** [laravel/ui#11]
This could more appropriate wat to separate Ui(presets) and Auth(auth views, route, controllers).

**What `Ui` package can do?**
Create presets for bootstrap, vue and react likewise.

**What `Auth` package can do?**
Auth package will export Auth controller directory(LoginController, RegisterController, and other auth controllers), Register Route.
Also, Auth views can be exported from this auth package.
__By this you can remove all Auth related controllers from laravel project and if user require user can get this via `auth` package__

**Comment by rgjchandler** [comment]
I don't think there's any need for this personally. 

The Auth scaffolding might seem redundant if you're just using the regular presets and basic view stubs, but creating another package creates another thing to maintain and something else to require when you eventually realise that you do need a quick and easy Authentication system.
