### ISSUE TITLE
Add ability to disable auto login after registration

### ISSUE THREAD

**Issue by akulmehta** [laravel/ui#117]
In previous versions where things were part of the RegisterController we could disable auto login by commenting out the `$this->guard()->login($user)`. However, now that it is moved to the auth-backend in laravel ui, we would have to do so by changing vendor files. This makes updating and using composer break changes. It would be good if there was a way to pass arguments to the register function to disable auto-login after registration, or even redirect to a specific page.

**Comment by driesvints** [comment]
I don't understand what you mean. This trait has always lived in the vendor directory (in framework's foundation component). So you'd have to edit vendor anyway.

You can disable it by overwriting the `register` method in the `RegisterController`. Maybe Taylor would accept a PR for a boolean property (`$autoLogin = true` or something). Feel free to attempt a PR if you like.

**Comment by akulmehta** [comment]
I see my error. Sorry for that.
