### ISSUE TITLE
Foundation Zurb Support

### ISSUE THREAD

**Issue by lindsay-twoblacksheep** [laravel/ui#118]
Hi

Firstly let me say thank you for the great ui package, it has made life very easy so far.

I'd like to know if there is any support for Foundation planned or if you would consider adding it.
[Foundation](https://get.foundation/)

Many thanks and keep up the great work!
Lindsay

**Comment by driesvints** [comment]
Hi there. Please see the readme. We're not accepting new presets, sorry.

**Comment by lindsay-twoblacksheep** [comment]
Thanks for the response.
