### ISSUE TITLE
Double password hashing in vanilla install?

### ISSUE THREAD

**Issue by omizzy** [laravel/ui#125]
Running through the installation instructions, I seem to run into the issue where login attempts (after logout from initial successful registration) fail to due password mismatching. I traced it down to here. It seems that `User::create()` also applies its own logic to safe guard the password. When I replace this line with `'password' => $data['password'],`, everything works as expected and the password still remains hashed in the database.

https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/stubs/Auth/RegisterController.stub#L70

**Comment by driesvints** [comment]
Feel free to adjust his in your own app.
