### ISSUE TITLE
VerifiesEmails send standard Response instead of JsonResponse

### ISSUE THREAD

**Issue by GSpecDrum** [laravel/ui#129]
- UI Version: 2.0.3
- Laravel Version: 7.12.0
- PHP Version: 7.4.5
- Database Driver & Version: MariaDB 10.4

### Description:

VerifiesEmails  trait send standard Illuminate\Http\Response when he should send JsonResponse.
see code:

https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/auth-backend/VerifiesEmails.php#L85
https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/auth-backend/VerifiesEmails.php#L60

**Comment by driesvints** [comment]
You need to pass along the correct Accept header: `application/json`.

**Comment by GSpecDrum** [comment]
When I send Accept:application/vnd.api+json , it return Content-Type:text/html; charset=UTF-8 header with 202 status and debug information.

When I send Accept:application/json header, it return 202 status and Content-Type:text/html; charset=UTF-8 header too, but with empty body.

see also this line:
https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/auth-backend/VerifiesEmails.php#L93


Your other traits in this package return JsonResponse:
https://github.com/laravel/ui/blob/397ff4b6f1099875f9d2dd1856cd1fb0a033d7f3/auth-backend/SendsPasswordResetEmails.php#L76
https://github.com/laravel/ui/blob/ec838c75ba1886d014c5465b1ecc79b2071f46c7/auth-backend/ResetsPasswords.php#L140

**Comment by driesvints** [comment]
The current responses are fine for empty bodies.

**Comment by GSpecDrum** [comment]
If you consider so, then OK.
I thought the response Content-Type header should depends on request Accept header, with any body: with content, or without.
Thank you anyway.
