### ISSUE TITLE
Cannot upgrade Laravel 6x to 7x

### ISSUE THREAD

**Issue by serojatech** [laravel/ui#133]
- UI Version: 1.2
- Laravel Version: 6.x
- PHP Version: 7.4
- Database Driver & Version: 8.0.9

### Steps To Reproduce:
I has followed the upgrade guide.
https://laravel.com/docs/7.x/upgrade#updating-dependencies

When I run composer update:
```
Problem:
    - Conclusion: don't install laravel/framework v7.0.0
    - laravel/ui v1.2.0 requires illuminate/support ~5.8|^6.0 -> satisfiable by laravel/framework[v6.18.35, 5.8.x-dev, 6.x-dev],
```

If I composer require laravel/ui "2.0" I got error that require Laravel 7.
```
Problem:
    - Conclusion: remove laravel/framework v6.18.35
    - Conclusion: don't install laravel/framework v6.18.35
    - laravel/ui 2.x-dev requires illuminate/support ^7.0 -> satisfiable by laravel/framework[7.x-dev],
```

Can someone help me with issue?

**Comment by driesvints** [comment]
As the composer error message says, you need to upgrade to Laravel 7.

**Comment by driesvints** [comment]
Ah, sorry. I misread your message. You probably have some outdated dependencies. Try removing your `composer.lock` file and `vendor` directory and run a composer install after you'd adjusted your dependencies in `composer.json`.

**Comment by serojatech** [comment]
I can't upgrade to Laravel 7. When I upgrade to Laravel 7 then I got this error.

```
Problem:
    - Conclusion: don't install laravel/framework v7.0.0
    - laravel/ui v1.2.0 requires illuminate/support ~5.8|^6.0 -> satisfiable by laravel/framework[v6.18.35, 5.8.x-dev, 6.x-dev],
```

**Comment by driesvints** [comment]
Please paste your `composer.json`.

**Comment by serojatech** [comment]
> Please paste your `composer.json`.
```
        "php": "^7.2",
        "barryvdh/laravel-dompdf": "^0.8.6",
        "fideloper/proxy": "^4.0",
        "jenssegers/date": "^3.5",
        "lab404/laravel-impersonate": "^1.6",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^1.2",
        "laravelcollective/html": "^6.0",
        "livewire/livewire": "^1.0",
        "maatwebsite/excel": "^3.1",
        "owen-it/laravel-auditing": "^10.0",
        "spatie/laravel-medialibrary": "^7.0.0",
        "spatie/laravel-permission": "^3.8",
        "te7a-houdini/laravel-trix": "^2.0",
        "yajra/laravel-datatables-oracle": "~9.0"
```

> Try removing your composer.lock file and vendor directory and run a composer install after you'd adjusted your dependencies in composer.json.

I did that yesterday, and run composer install -vvv and wait for more than 5hours but stuck here like 'forever' :(

```
Reading /Users/macuser/.composer/cache/repo/https---repo.packagist.org/provider-nunomaduro$collision.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #23)
```

No sure what's the real problem is. Thank you for time.

**Comment by driesvints** [comment]
So you've said:

> I has followed the upgrade guide.

But I think you need to read it a bit more carefully since `laravel/ui` hasn't been updated to 2.0 in your composer.json. Laravel is even still set to 6.2.

Please read the full upgrade guide first.

<img width="782" alt="Screenshot 2020-08-16 at 16 54 44" src="https://user-images.githubusercontent.com/594614/90337200-3d75fe00-dfe1-11ea-9097-0478665de742.png">

**Comment by serojatech** [comment]
>But I think you need to read it a bit more carefully since laravel/ui hasn't been updated to 2.0 in your composer.json. Laravel is even still set to 6.2.

Sorry, the previous composer.js is the one before I upgrade or make change.
Below is the latest.

```
"require": {
        "php": "^7.2.5",
        "barryvdh/laravel-dompdf": "^0.8.6",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "jenssegers/date": "^3.5",
        "lab404/laravel-impersonate": "^1.6",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.24",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "laravelcollective/html": "^6.0",
        "livewire/livewire": "^1.0",
        "maatwebsite/excel": "^3.1",
        "owen-it/laravel-auditing": "^10.0",
        "spatie/laravel-medialibrary": "^7.0.0",
        "spatie/laravel-permission": "^3.8",
        "te7a-houdini/laravel-trix": "^2.0",
        "yajra/laravel-datatables-oracle": "~9.0"
    },
"require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
```

Any help would be much appreciated.

**Comment by driesvints** [comment]
Did you remove your composer.lock and vendor directory and run composer install like I suggested here? https://github.com/laravel/ui/issues/133#issuecomment-674508946

**Comment by serojatech** [comment]
Yes I did that yesterday. After I remove composer.lock and vendor directory and run composer install. The installation process stuck here. waited for 5hours+ nothing happen.
```
Reading /Users/macuser/.composer/cache/repo/https---repo.packagist.org/provider-nunomaduro$collision.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #23)
```

I also run composer clearcache but no luck. 2 days ago I used Laravel Shift it also stuck when I composer update.
I got this error the same as the one I try manually upgrade.
```
Problem:
    - Conclusion: don't install laravel/framework v7.0.0
    - laravel/ui v1.2.0 requires illuminate/support ~5.8|^6.0 -> satisfiable by laravel/framework[v6.18.35, 5.8.x-dev, 6.x-dev],
```

**Comment by driesvints** [comment]
@serojatech I've tried it out for you and it seems that `jenssegers/date` needs to be updated to `^4.0`. Try that and remove your composer.lock and composer.json again.

**Comment by serojatech** [comment]
@driesvints you are the man, lifesaver. I wish I could buy you a drink. Thank you so much for your precious time. Can't wait for Laravel UI Kit 🚀
