### ISSUE TITLE
Package phpunit/php-token-stream is abandoned

### ISSUE THREAD

**Issue by NatusPella** [laravel/ui#134]
- UI Version: 2.1.0
- Laravel Version: 7.25.0
- PHP Version: 7.3.3
- Database Driver & Version: SQLite

### Description:
When installing `laravel/ui` I received this message:
`Installing laravel/ui (v2.1.0): Downloading (100%) Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.`

### Steps To Reproduce:
1. Create a Laravel project
2. Execute `composer require laravel/ui`

**Comment by driesvints** [comment]
This package doesn't uses that.

**Comment by matheusrgg** [comment]
@NatusPella this is also happening to me when I start a new laravel project.

**Comment by vitorfleite** [comment]
It is also happening with me.

Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested

**Comment by aetonsi** [comment]
New Laravel projects (`composer create-project --prefer-dist laravel/laravel blog`) have `phpunit/phpunit` as dev dependency.

This is the dependency tree to the incriminated package:
`phpunit/phpunit` > `phpunit/php-code-coverage` > `phpunit/php-token-stream`

**Comment by joni2back** [comment]
Same issue on my end requiring dev         "phpunit/phpunit": "^8.5"

**Comment by sebastianbergmann** [comment]
`phpunit/php-token-stream` has been abandoned. PHPUnit 8.5, which still receives bug fixes until February, uses `phpunit/php-token-stream`. Just ignore this message from Composer.

**Comment by GayanSandaruwan** [comment]
Above is just a warning! If you get an error while upgrading laravel to 7.x the real error failing the update would be something like,
`PHP Fatal error:  Declaration of App\Exceptions\Handler::report(Exception $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Throwable $e) in /home/education/Repositories/VIMS -6/app/Exceptions/Handler.php on line 35`
The above is just a warning. In my case to solve above problem replace the said while with [https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php](url)

**Comment by muktaahammed** [comment]
It is just a warning you can ignore it.

it is requested by a third-party dependency not by Laravel itself. So when this dependency gets updated by its mantainer this message will disappear.

**I got it from another blog. This problem I faced when I try to build a project using Slim Framework**

**Comment by husonghua** [comment]
You can update to phpunit 9.0 or above to avoid the warning

**Comment by maratkh** [comment]
Its a not only warning, it goin to error in Generating optimized autoload files
 because [RuntimeException]                                                                                                
  Could not scan for classes inside "/home/vagrant/code/backend/test/vendor/phpunit/php-code-coverage/sr  
  c/" which does not appear to be a file nor a folder

**Comment by thapaprogress** [comment]
whats the solution for above issues.
