### ISSUE TITLE
Return valid json response from register endpoint

### ISSUE THREAD

**Issue by jorenvanhee** [laravel/ui#137]
The register endpoint currently does not return a valid empty json response.

```php
return $request->wantsJson()
    ? new Response('', 201)
    : redirect($this->redirectPath());
```

A lot of javascript libraries will throw an error on this.
- [jquery (since 1.9)](https://jquery.com/upgrade-guide/1.9/#jquery-ajax-returning-a-json-result-of-an-empty-string)
- [ky (throws on empty 201, made an exception for 204)](https://github.com/sindresorhus/ky/issues/193)
- [Angulars http client](https://stackoverflow.com/questions/57404556/angular-httpclient-error-with-empty-200-201-response-always-calls-json-parse#:~:text=1%20Answer&text=A%20server%20that%20returns%20response,is%20not%20parsed%20as%20JSON.)

This probably can't be changed easily since it's breaking. But maybe someday.

**Comment by driesvints** [comment]
You need to pass the correct accept header

**Comment by jorenvanhee** [comment]
Thanks for the quick reply. `"Accept":"application/json"` is being passed since `wantsJson()` returns true. And then it returns a response with an empty string `''`.  I believe `{}` would be better (valid json response).

**Comment by driesvints** [comment]
Thanks, that's clear. Sent in a PR for this: https://github.com/laravel/ui/pull/139
