### ISSUE TITLE
Auth::routes() gives a namespace error on LoginController

### ISSUE THREAD

**Issue by bramceulemans** [laravel/ui#138]
- UI Version: 2.2.0
- Laravel Version: 8.x-dev
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:

`Auth::routes()` gives a namespace error on LoginController.

I have this code snipped in my `routes/web.php`

```php
Auth::routes([
    'register' => false,
    'reset' => true,
    'confirm' => false,
    'verify' => false,
]);
```

![image](https://user-images.githubusercontent.com/13304739/92183732-833f1d00-ee4f-11ea-867d-4e17f22f7551.png)

and it gives an error on the LoginController, saying it can't find the class.

### Suggested changes

In the `src/AuthRouteMethods.php`, the route bindings should be changed to the new syntax:

```php
    /**
     * Register the typical authentication routes for an application.
     *
     * @param  array  $options
     * @return callable
     */
    public function auth()
    {
        return function ($options = []) {
            // Login Routes...
            if ($options['login'] ?? true) {
                $this->get('login', [LoginController::class, 'showLoginForm'])->name('login');
                $this->post('login', [LoginController::class, 'login']);
            }

            // other routes...
        };
    }
```

### Workaround

I found a workaround to this problem, and it's to wrap the `Auth::routes()`:

```php
// FIXME: remove this nasty hack to get auth routes working
Route::namespace('App\\Http\\Controllers')->group(function (): void {
    Auth::routes([
        'register' => false,
        'reset' => true,
        'confirm' => false,
        'verify' => false,
    ]);
});
```

**Comment by driesvints** [comment]
Please use jetsream for new installs.

**Comment by bramceulemans** [comment]
Is `laravel/ui` not supported anymore?

**Comment by bramceulemans** [comment]
> Please use jetsream for new installs.

What about people that don't want to use Livewire, Inertia of Tailwind?

I think plenty of developers don't need the overhead or complexity of Livewire. It definitely has it's use case, but the thing I liked about `laravel/ui` is how simple it was. Just plain Bootstrap views with some auth controllers that you can always implement or peek inside on how authentication is done.

The idea of Jetstream is great, I've tried it already and offers so much functionality out of the box. It would just be great if this package wouldn't be deprecated and continue to exist/be fully compatible, not everyone needs the complexity of Jetstream and Fortify.

**Comment by driesvints** [comment]
@bramceulemans we still accept prs for bugfixes but aren't planning on developing new features for laravel/ui. You're free to fork the repo and maintain a fork yourself if you want.
