### ISSUE TITLE
sendLoginResponse() etc method names are misleading

### ISSUE THREAD

**Issue by szepeviktor** [laravel/ui#140]
When an English speaker reads `sendLoginResponse` s/he thinks: _this method will actually send the response to the client._

But it does a `@return \Illuminate\Http\Response` - thus returns a value.
Please consider naming those methods `getLoginResponse` etc.
Thank you.

**Comment by driesvints** [comment]
It's not worth the breaking change.

**Comment by szepeviktor** [comment]
For googlers: `sendLockoutResponse` is not a regular method, it throws an Exception unconditionally.
