### ISSUE TITLE
Update Auth routes to work with laravel 8.*

### ISSUE THREAD

**Issue by orhanasllani** [laravel/ui#141]
- UI Version: 2.2.1
- Laravel Version: 8.0
- PHP Version: 7.4.7
- Database Driver & Version: mysql

### Description:
Update Routes
From this
if ($options['register'] ?? true) {
    $this->get('register', 'Auth\RegisterController@')->name('register');
    $this->post('register', 'Auth\RegisterController@register');
 }
to this
if ($options['register'] ?? true) {
     $this->get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    $this->post('register', [RegisterController::class, 'register']);
 }
### Steps To Reproduce:
just go to register route on browser

**Comment by driesvints** [comment]
Use Jetstream for new Laravel apps. Existing apps will continue to work because they still have the namespace in their route service provider.

**Comment by Kovah** [comment]
Does that mean that this package is kinda deprecated? I tried Jetstream and find it _super hard_ to get started because it forces you into using Livewire or Intertia.

**Comment by orhanasllani** [comment]
> Does that mean that this package is kinda deprecated? I tried Jetstream and find it _super hard_ to get started because it forces you into using Livewire or Intertia.

i fixit by editing AuthRoutes...Somthing under Laravel/UI namespace

working 100%

<?php

namespace Laravel\Ui;

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;



class AuthRouteMethods
{
    /**
     * Register the typical authentication routes for an application.
     *
     * @param  array  $options
     * @return callable
     */
    public function auth()
    {
        return function ($options = []) {
            // Login Routes...
            if ($options['login'] ?? true) {
                $this->get('login', [LoginController::class, 'showLoginForm'])->name('login');
                $this->post('login', [LoginController::class, 'login']);
            }

            // Logout Routes...
            if ($options['logout'] ?? true) {
                $this->post('logout', [LoginController::class, 'logout'])->name('logout');
            }

            // Registration Routes...
            if ($options['register'] ?? true) {
                $this->get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
                $this->post('register', [RegisterController::class, 'register']);
            }

            // Password Reset Routes...
            if ($options['reset'] ?? true) {
                $this->resetPassword();
            }

            // Password Confirmation Routes...
            if ($options['confirm'] ??
                class_exists($this->prependGroupNamespace(ConfirmPasswordController::class))) {
                $this->confirmPassword();
            }

            // Email Verification Routes...
            if ($options['verify'] ?? false) {
                $this->emailVerification();
            }
        };
    }

    /**
     * Register the typical reset password routes for an application.
     *
     * @return void
     */
    public function resetPassword()
    {
        return function () {
            $this->get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
            $this->post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
            $this->get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
            $this->post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
        };
    }

    /**
     * Register the typical confirm password routes for an application.
     *
     * @return void
     */
    public function confirmPassword()
    {
        return function () {
            $this->get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
            $this->post('password/confirm', [ConfirmPasswordController::class, 'confirm']);
        };
    }

    /**
     * Register the typical email verification routes for an application.
     *
     * @return void
     */
    public function emailVerification()
    {
        return function () {
            $this->get('email/verify', [VerificationController::class, 'show'])->name('verification.notice');
            $this->get('email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify');
            $this->post('email/resend', [VerificationController::class, 'resend'])->name('verification.resend');
        };
    }
}

**Comment by driesvints** [comment]
You aren't forced to use anything. Just `laravel new app`. Also: the livewire stack is just blade. You don't *have* to use livewire anywhere else in your app.

**Comment by orhanasllani** [comment]
edit AuthRoutes.... Something under Laravel/UI Namespace

`<?php

namespace Laravel\Ui;

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;



class AuthRouteMethods
{
    /**
     * Register the typical authentication routes for an application.
     *
     * @param  array  $options
     * @return callable
     */
    public function auth()
    {
        return function ($options = []) {
            // Login Routes...
            if ($options['login'] ?? true) {
                $this->get('login', [LoginController::class, 'showLoginForm'])->name('login');
                $this->post('login', [LoginController::class, 'login']);
            }

            // Logout Routes...
            if ($options['logout'] ?? true) {
                $this->post('logout', [LoginController::class, 'logout'])->name('logout');
            }

            // Registration Routes...
            if ($options['register'] ?? true) {
                $this->get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
                $this->post('register', [RegisterController::class, 'register']);
            }

            // Password Reset Routes...
            if ($options['reset'] ?? true) {
                $this->resetPassword();
            }

            // Password Confirmation Routes...
            if ($options['confirm'] ??
                class_exists($this->prependGroupNamespace(ConfirmPasswordController::class))) {
                $this->confirmPassword();
            }

            // Email Verification Routes...
            if ($options['verify'] ?? false) {
                $this->emailVerification();
            }
        };
    }

    /**
     * Register the typical reset password routes for an application.
     *
     * @return void
     */
    public function resetPassword()
    {
        return function () {
            $this->get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
            $this->post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
            $this->get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
            $this->post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
        };
    }

    /**
     * Register the typical confirm password routes for an application.
     *
     * @return void
     */
    public function confirmPassword()
    {
        return function () {
            $this->get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
            $this->post('password/confirm', [ConfirmPasswordController::class, 'confirm']);
        };
    }

    /**
     * Register the typical email verification routes for an application.
     *
     * @return void
     */
    public function emailVerification()
    {
        return function () {
            $this->get('email/verify', [VerificationController::class, 'show'])->name('verification.notice');
            $this->get('email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify');
            $this->post('email/resend', [VerificationController::class, 'resend'])->name('verification.resend');
        };
    }
}
`

**Comment by barryvdh** [comment]
You could just put a Route group with the 'App\Http\Controllers' around the Auth::routes() call in your own code, right?

**Comment by BCleverly** [comment]
As @barryvdh says, wrap the auth routes in a group to get them working. I had to do this in a project recently, my implementation doing it:

web.php
```php
<?php

Route::group(['namespace' => 'App\\Http\\Controllers'], function() {
    Auth::routes(['register' => false]);
});
```

RouteServiceProvider.php
```php
<?php
class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = '';
```

Might be worth adding this to the docs/readme for people wanting to make use of UI if they just want the simple auth scaffolding?

**Comment by barryvdh** [comment]
I suggested a possible solution in #143, can you try that out?

**Comment by rajjanorkar** [comment]
Thats works @barryvdh adding namespace to routeserviceprovider, thank you.

**Comment by rajjanorkar** [comment]
however i am not sure about the future of this package...

**Comment by barryvdh** [comment]
Laravel 8 is supported in v3

**Comment by jrdutra** [comment]
Where is the App/Http/Controllers/Auth dir in Laravel 8??

**Comment by fahadasif252** [comment]
SAME thing happend with me .
so did you get your answer how did we can change route links in laravel 8 using jetstream and livewire

**Comment by syntrio-sadiik** [comment]
Route::get('/sample', [SampleController::class, 'index']);
