### ISSUE TITLE
ui --auth broken on laravel 8

### ISSUE THREAD

**Issue by rroethof** [laravel/ui#142]
- UI Version: ^2.2
- Laravel Version: 8.0.0
- PHP Version: 7.4.10

### Description:
 when running 'standard' auth scaffolding as known in 7 (which is the default when searching online for tutorials etc) breaks in laravel 8....

`php artisan ui bootstrap --auth` or `php artisan ui vue --auth` will result in a "**Target class [Auth\LoginController] does not exist.**"

This can be fixed by changing your route file to
```
Route::namespace('App\Http\Controllers')->group(function () {
Auth::routes();
});
```
but the CSS will still be broken.. I think someone missed that at laravel, cause the only other option is to use jetstream in their documentation, which for some projects or updates is not a option and there is 0 documentation anymore on the ui --auth option.

### Steps To Reproduce:
```
composer create-project --prefer-dist laravel/laravel .

composer require laravel/ui

php artisan ui bootstrap --auth

npm install && npm run dev

php artisan migrate

php artisan db:seed
```

**Comment by hananloser** [comment]
on RouteServiceProvider add $namspace = App\Http\Controllers

**Comment by hananloser** [comment]
> * UI Version: ^2.2
> * Laravel Version: 8.0.0
> * PHP Version: 7.4.10
> 
> ### Description:
> when running 'standard' auth scaffolding as known in 7 (which is the default when searching online for tutorials etc) breaks in laravel 8....
> 
> `php artisan ui bootstrap --auth` or `php artisan ui vue --auth` will result in a "**Target class [Auth\LoginController] does not exist.**"
> 
> This can be fixed by changing your route file to
> 
> ```
> Route::namespace('App\Http\Controllers')->group(function () {
> Auth::routes();
> });
> ```
> 
> but the CSS will still be broken.. I think someone missed that at laravel, cause the only other option is to use jetstream in their documentation, which for some projects or updates is not a option and there is 0 documentation anymore on the ui --auth option.
> 
> ### Steps To Reproduce:
> ```
> composer create-project --prefer-dist laravel/laravel .
> 
> composer require laravel/ui
> 
> php artisan ui bootstrap --auth
> 
> npm install && npm run dev
> 
> php artisan migrate
> 
> php artisan db:seed
> ```

https://github.com/laravel/laravel/commit/58a98efb86c0c0a819e333a52eccf2a7de652f15#diff-b467cc786635bd6945b17726282f1c64

**Comment by driesvints** [comment]
Please use jetstream for new Laravel projects.

**Comment by rroethof** [comment]
I do understand the push towards jetstream, but you have to acknowledge that 99.99% of the existing documentation on laravel and authentication use the old method and older projects cant just migrate..

therefore just plain 'dropping'  laravel/ui would imho be a unwise path to go, or at least create a migration path / support end time on it.

**Comment by driesvints** [comment]
I don't understand what you mean. Nothing is broken for existing apps. You own all the code from the scaffold.

**Comment by rroethof** [comment]
Well when I would git clone a project, therefore need to composer install/composer update
Then I would also run into this issue

**Comment by barryvdh** [comment]
@rroethof Does https://github.com/laravel/ui/pull/143 solve your issue?

**Comment by rroethof** [comment]
Will test asap, working on new project, with jetstream atm ;)
