### ISSUE TITLE
Laravel now uses postCss instead of sass for Mix causing empty CSS with UI

### ISSUE THREAD

**Issue by JuanDMeGon** [laravel/ui#144]
- UI Version: 2.3.0
- Laravel Version: 8.0.3
- PHP Version: 7.4
- Database Driver & Version: Not applicable

### Description:
Currently, Laravel 8 is using postCss, instead of sass in the default webpack.mix.js file (https://github.com/laravel/laravel/commit/588247b790f4f0d13296247f8140b1466e1e6936#diff-61877038a5575038809abf03f0009520R15). This causes that, even after installing Laravel UI and requesting any assets like bootstrap, after compiling it still being an empty CSS.

The correct behavior should be that Laravel UI changes the webpack.mix.js file, changing the usage of postCss to sass in order to get it working immediately after following the proper instructions given by Laravel UI:

"XXXXX scaffolding installed successfully. Please run "npm install && npm run dev" to compile your fresh scaffolding."

### Steps To Reproduce:
Create a fresh Laravel 8 project. Add Laravel UI as a dependency, then execute php artisan ui bootstrap --auth, follow the instructions executing npm install followed by npm run dev. This will bring a completely empty CSS file.

Thanks, guys!

**Comment by driesvints** [comment]
I've sent in a PR for this here: https://github.com/laravel/ui/pull/146

**Comment by JuanDMeGon** [comment]
Thanks! That was so fast.
Best wishes to you all.
