### ISSUE TITLE
laravel 8 use ui or  Jetstream?

### ISSUE THREAD

**Issue by victorbuild** [laravel/ui#150]
- UI Version: 2.3.0
- Laravel Version: 8.0.0
- PHP Version: 7.4.6

### Description:
laravel 8 use ui or  Jetstream?

### Steps To Reproduce:

1. laravel new testlaravel8
2. composer require laravel/ui 
3.  Pull requests https://github.com/laravel/ui/pull/147 but close
4. test Jetstream but today look Merge https://github.com/laravel/ui/commit/90a70c9a150c51c9405b2cfae6bd445f80d4237b

**Comment by rogervila** [comment]
If you want laravel/ui auth scaffolding for Laravel 8 try this fork: https://github.com/rogervila/laravel-legacy-ui

**Comment by driesvints** [comment]
We recommend Jetstream but laravel/ui has been patched as well in the meantime.
