### ISSUE TITLE
User Model Namespace

### ISSUE THREAD

**Issue by assellalou** [laravel/ui#152]
- UI Version: latest
- Laravel Version: latest
- PHP Version: 7.4
- Database Driver & Version: Idk

### Description:

When I require laravel/ui and run it on my project with --auth flag it generates the Controllers/Auth folder nothing odd about it except for the registration controller it still tries to fetch the User Model from /App/User instead of /App/Models/User

### Steps To Reproduce:

run php artisan ui vue --auth 
Try of register a new user or just check /App/Http/Controllers/Auth/RegisterController.php create() method.

**Comment by driesvints** [comment]
Yes we're aware. We're looking into this.
