### ISSUE TITLE
Support Laravel 8.x

### ISSUE THREAD

**Issue by woodspire** [laravel/ui#156]
Laravel 8.1.0 was released and this package doesn't support it.
I know that jetstream is the new way, but for people which migrated from laravel 7, they are still using laravel/ui.

**Comment by alxmtr** [comment]
laravel/ui v3.0 has been released today and is compatible with Laravel 8.

```
composer require laravel/ui:^3.0
```

**Comment by woodspire** [comment]
Laravel/ui version 3 did the trick. Thanks
