### ISSUE TITLE
This repo should not be depricated

### ISSUE THREAD

**Issue by fractalf** [laravel/ui#157]
I would strongly argue that telling users not to use this repo and instead only use the new Laravel Jetstream stack is a bad idea. I do get it, you want to front the new stack, that's fine, but telling users this is the "only" options wasn't helping us at least.

I tried the Jetstream/Inertia stack for a few days I can say straight away it's not for our company/team. The docs say you don't have to use Tailwind etc, but that doesn't really make sense as it is very tightly coupled with everything you get from that package.
I mean, it looks great on paper, and it works fine, but there's a huge overhead in learning how to do things the "Inertia" way etc. That's a big cost to put on a team that works very well with a pure VueJS frontend and a PHP backend. I could say more about this, but you get the idea.

I'm very happy this repo was updated for Laravel 8. This is a much cleaner approach if you just want to use Laravel + VueJS. There's even a good bunch of things that could be upgraded to make it closer to developing with Vue CLI (I'm willing to contribute).

So, anyway, Laravel **should definetly** support a lightweight scaffold scheme like this for user just wanting to get up and running quickly with VueJS/React etc.

**Comment by driesvints** [comment]
We're still allowing for bug fixes to be sent in. This is open source and anyone can contribute. We have no plans on developing new features for laravel/ui.

**Comment by fractalf** [comment]
May I ask why you are discouraging users to use this?
I mean, recommending it is fine, but telling uses "you shouldn't use this"?
Like I said, this is much more suited for our use cases.

Thanks

**Comment by driesvints** [comment]
We don't want to maintain this ourselves anymore.

**Comment by rconte84** [comment]
> We don't want to maintain this ourselves anymore.

When you say "We don't want to maintain..." you mean that only bugs for Laravel 8 will be fixed and so there will be not a support for future migration of laravel major releases? What we must expect on ~April 2021 for Laravel 9?

**Comment by driesvints** [comment]
@rconte84 there's been a lot going back and forward since this post. We're still maintaining Laravel UI but won't be actively developing features for it anymore. We are still going to be supporting future Laravel versions however.
