### ISSUE TITLE
Routes custom namespace requires now a LoginController

### ISSUE THREAD

**Issue by anibalsanchez** [laravel/ui#158]
- UI Version: 2.4.0
- Laravel Version: 7.28.2
- PHP Version: 7.4.3
- Database Driver & Version: 7.4.3

### Description:

After updating to the latest v7.28, I'm finding that the Auth routes require to create a `LoginController` to load the custom namespace. 

This is the commit that changed the previous routes namespace load: 

https://github.com/laravel/ui/commit/c1c548ffd89a55b93be410e041096790a6b1c19e#diff-df616a811ee88af131d374bfbe8dbe1f

### Steps To Reproduce:

1. Define a custom namespace in the RouteServiceProvide:

```php
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'MyApplication\\Http\\Controllers';
``` 

2. Create a custom `RegisterController.php` on `MyApplication\\Http\\Controllers`.

3. It is no loaded unless you create a `LoginController`.

CC @barryvdh

**Comment by barryvdh** [comment]
You could update the check to check for alle the controllers perhaps.

**Comment by anibalsanchez** [comment]
Do you mean that `src/AuthRouteMethods.php` must be changed to regain the previous behavior checking for the presence of the namespace+controller in each route definition?

**Comment by barryvdh** [comment]
I mean this check here: https://github.com/laravel/ui/blob/ff6af4f0bc5a5bfe73352cdc03dbfffc4ace92d8/src/AuthRouteMethods.php#L16

to something like this:
```php
if (
		class_exists($this->prependGroupNamespace('Auth\LoginController')) 
		|| class_exists($this->prependGroupNamespace('Auth\RegisterController@register'))
	) {
	$namespace = null;
} else {
	$namespace = 'App\Http\Controllers';
}```

But yeah, it currently fails if you don't have a login controller.

**Comment by anibalsanchez** [comment]
Ok, then it is a bug and unintended effect of the change.

I think that the same logic should also be applied to all the 6 controllers referenced in the rest of Auth routes.

**Comment by driesvints** [comment]
@barryvdh can't we revert your changes now that we have a separate release for Laravel 8?

**Comment by barryvdh** [comment]
We could.

**Comment by barryvdh** [comment]
Probably Laravel 8 users should use 3.x anyways.

**Comment by driesvints** [comment]
I've sent in https://github.com/laravel/ui/pull/160

**Comment by driesvints** [comment]
Will be reverted in the next patch on Tuesday

**Comment by anibalsanchez** [comment]
Thanks @driesvints !

**Comment by redgluten** [comment]
I think there is still an edge-case here unless I’m missing something? The whole authentication setup has always been a bit obscure to me. Here’s my situation:

- Laravel: v7.28.4 (stuck there for the time being because PHP 7.2)
- laravel/ui: v2.4.1
- livewire: v2.2.9

In order to use Livewire full page components I need to remove the route namespacing and use the newer array syntax for other routes (`[MyController::class, 'methodName']). But then it breaks as described in #138.

Is there a way to circumvent this?

**Comment by driesvints** [comment]
@redgluten please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
