### ISSUE TITLE
Readme / Instructions on how to use laravel/ui

### ISSUE THREAD

**Issue by connecteev** [laravel/ui#17]
Can someone explain how / when one should use this repo? Couldn't find a readme, and it's hard to understand what this is supposed to do. Since this is a first-party package from Taylor I'm interested.

**Comment by driesvints** [comment]
You can read the docs here but we should indeed add a readme soon.

https://laravel.com/docs/6.0/frontend

**Comment by connecteev** [comment]
Actually just this link is super useful..thanks.

**Comment by driesvints** [comment]
Sent in a PR
