### ISSUE TITLE
route:cache artisan command failed in laravel 8 with this UI package

### ISSUE THREAD

**Issue by dimahali** [laravel/ui#170]
- UI Version: latest
- Laravel Version: 8.*
- PHP Version: 7.3
- Database Driver & Version: MYSQL

### Description:

I have configured a laravel 8 application and used this UI package for auth. But when i try to run ` route:cache` artisan command I get this error:

``Unable to prepare route [login] for serialization. Another route has already been assigned name [login].``

I have used both `Auth::routes()` and complete routes in the `web.php` routes file but still get the error...

### Steps To Reproduce:

Install laravel 8.*
use this UI package for auth scaffolding
try running `route:cache` artisan command

**Comment by dimahali** [comment]
I guess I have found the issue. I installed both fortify and UI packages. Both are registering routes for auth which is causing the problem if I am not wrong...

**Comment by driesvints** [comment]
@dimahali yeah you can't install both. Have to be one or the other.
