### ISSUE TITLE
Unknown argument: --hide-modules or --no-progress

### ISSUE THREAD

**Issue by PankovAlxndr** [laravel/ui#174]
- UI Version: ^3.0
- Laravel Version: ^8.0
- PHP Version: 7.4

### Description:
Unknown argument: --hide-modules or --no-progress (dev or prod env)

### Steps To Reproduce:

i have installed fresh version of laravel

i have installed fresh version of laravel \ ui

I have
- node v15.0.1
- npm 7.0.3

(I have package.json and webpack.mix.js file)

i run npm install

i want to execute npm run dev

but I get this message: Unknown argument: --hide-module

![2020-10-26_21-15-37](https://user-images.githubusercontent.com/3092550/97212271-359cbc00-17d1-11eb-9aab-a0da4af709aa.png)

**Comment by curant** [comment]
The flag `--hide-modules` does not exist anymore in webpack-cli 4.

**Comment by driesvints** [comment]
I've sent in a PR to remove this flag in the skeleton. In the meantime you can do the same in your package.json: https://github.com/laravel/laravel/pull/5460
