### ISSUE TITLE
Add laravel/breeze alongside laravel/Jetstream in the suggested alternative of the Readme disclaimer 

### ISSUE THREAD

**Issue by khalyomede** [laravel/ui#181]
So that more people are aware of this alternative to scaffold authentication systems based on laravel/breeze

**Comment by driesvints** [comment]
People can still choose.

**Comment by khalyomede** [comment]
Hopefully people have the choice. This issue goal is to let people **be aware** these solutions exist in the Laravel package ecosystem.
