### ISSUE TITLE
Auth doesn't send notification emails out

### ISSUE THREAD

**Issue by i-fail** [laravel/ui#182]
- UI Version: 3.1
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: 

### Description:

Emails aren't sent on Auth user registration / verification

### Steps To Reproduce:
I did all of the things below:

// User authentication routes
`Auth::routes(['verify' => true]);`

// MustVerifyEmail interface
`class User extends Authenticatable implements MustVerifyEmail`

Entered all the credentials into **.env**

```
MAIL_MAILER=mailjet
MAIL_DRIVER=mailjet
MAILJET_APIKEY=3acaf7...
MAILJET_APISECRET=34974...
```

Entered the transport string into config\mail.php

	'default' => env('MAIL_MAILER', 'mailjet'),
	'mailers' => [
		'mailjet' => [
			'transport' => 'mailjet',
		],
Added config/services.php

	'mailjet' => [
			'key' => env('MAILJET_APIKEY'),
			'secret' => env('MAILJET_APISECRET'),
			'transactional' => [
				'call' => true,
				'options' => [
					'url' => 'api.mailjet.com',
					'version' => 'v3.1',
					'call' => true,
					'secured' => true
				]
			],
			'common' => [
				'call' => true,
				'options' => [
					'url' => 'api.mailjet.com',
					'version' => 'v3',
					'call' => true,
					'secured' => true
				]
			]
	]

Added providers to config/app.php

	// Mailjet
	Mailjet\LaravelMailjet\MailjetServiceProvider::class,
	Mailjet\LaravelMailjet\MailjetMailServiceProvider::class,

Yet when I go through the user registration process, email is not sent. No error of any kind. Just not sent.

Same if I navigate to <domain.com>/email/verify, and click on "click here to request another", no emails are sent. Just silent 302, no errors.

Here's proof that Auth::routes work fine, everything works fine. Except emails aren't being sent. 

https://www.youtube.com/watch?v=eMDy4ZSu2jY

When I manually call MailJet API with the same credentials, emails go out perfectly fine. It's just UI / Auth is not calling MailJet API.

I tried the same with simple SMTP instead of MailJet, same problem. Emails not sent.

**Comment by driesvints** [comment]
Since we don't officially support MailJet I'm going to have to redirect you to a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
