### ISSUE TITLE
Php artisan ui vue --auth throws array_key_exists() expects paramater 2 to be array, null given error,

### ISSUE THREAD

**Issue by spencerkphillips** [laravel/ui#188]
- UI Version: 3.1
- Laravel Version: 8.12
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.31

### Description:
When picking which scaffolding to use, I chose vue --auth. When I ran PHP artisan ui vue --auth, I get the errors ``array_key_exists() expects paramater 2 to be array, null given`` in vendor\laravel\ui\src\Presets\Preset.php:40 and
``ksort() expects parameter 1 to be array, null given`` in vendor\laravel\ui\src\Presets\Preset.php:48

### Steps To Reproduce:
Run composer require laravel/ui
Then run php artisan ui vue --auth

**Comment by driesvints** [comment]
Can't reproduce this sorry.
