### ISSUE TITLE
Home directory path in RedirectsUsers trait

### ISSUE THREAD

**Issue by tutkun** [laravel/ui#191]
https://github.com/laravel/ui/blob/964312989c99db1d5e3b307b833084b81ab58652/auth-backend/RedirectsUsers.php#L18

Wouldn't it be more appropriate to make the "**/home**" part here as **route('home')**? There is no **'/home'** in my route. Because I changed it. So I have to manipulate laravel/ui core files.

**Comment by driesvints** [comment]
Hey @tutkun. This has been asked quite a few times before. Since this file is part of your codebase you can adjust it how you want. We'd like to keep this as the default.
