### ISSUE TITLE
Uncaught TypeError: Vue.component is not a function

### ISSUE THREAD

**Issue by ashwin-nath-m** [laravel/ui#192]
- UI Version: 3.1.0
- Laravel Version: 8.21.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:

Unable to get vue scaffolding to work. Throwing Uncaught TypeError: Vue.component is not a function

### Steps To Reproduce:

1. Fresh install laravel 8
2. Add laravel/ui 
3. Run php artisan ui vue --auth
4. Add .vue() in webpack.mix,js
5. Load the site and look at the console logs.

**Comment by ashwin-nath-m** [comment]
Issue seems to be with v6.0.x of laravel-mix. Downgraded to lower version of laravel-mix to fix.

**Comment by JeffreyWay** [comment]
The solution is to always import Vue as an ES6 module.

```
import Vue from 'vue';
```

Otherwise, you'll have to append `.default` to the import:

```
let Vue = require('vue').default;
```

**Comment by driesvints** [comment]
Probably needs to be done here: https://github.com/laravel/ui/blob/3.x/src/Presets/vue-stubs/app.js#L9

@ashwin-nath-m can you try that and if it works send in a PR?

**Comment by JeffreyWay** [comment]
@driesvints I'll do it real quick.

**Comment by driesvints** [comment]
Thanks @JeffreyWay!
