### ISSUE TITLE
Can't disable register function laravel 8

### ISSUE THREAD

**Issue by adeguntoro** [laravel/ui#195]
- UI Version: 3.2
- Laravel Version: 8.22.0
- PHP Version: 7.3.3
- Database Driver & Version:

### Description:
Is it normal that i can't disable register function on Laravel 8 ?
or the only to do that by using Jetstream ?
### Steps To Reproduce:
i add this on my route config :
```
Auth::routes([

    'register' => false, // Register Routes...
  
    'reset' => false, // Reset Password Routes...
  
    'verify' => false, // Email Verification Routes...
  
]);
```

**Comment by driesvints** [comment]
Works fine for me. Make sure you're on the latest UI version.
