### ISSUE TITLE
Bootstrap 5 support?

### ISSUE THREAD

**Issue by Neeraj1005** [laravel/ui#196]
Today I installed fresh laravel8.x project with this `ui` package. And I think this package supports `bootstrap 4.x`. Does anyone know how to configure this package or I can add `bootstrap 5` to my project?
After installing bootstrap5 using npm command `npm install bootstrap@next` and then run `npm run dev` command gives me this kind of error.
```
ERROR in ./node_modules/bootstrap/dist/js/bootstrap.esm.js 6:0-41
Module not found: Error: Can't resolve '@popperjs/core' in 'C:\laragon\www\tasky\node_modules\bootstrap\dist\js'
```

**Comment by driesvints** [comment]
We're probably not going to support this ourselves. You can always try a pr if you like.
