### ISSUE TITLE
Other CSS Framework

### ISSUE THREAD

**Issue by dib258** [laravel/ui#20]
Hi,

I've read the documentation on laravel/ui on laravel.com and I find that the fact that these command are outside of the framework is a good choice.

I have a question / enhancement regarding the possibility to also switch CSS frameworks. For example, a possibility to switch from Bootstrap (which is already there) to Tailwind CSS (or some other CSS Framework) out of the box?

Hope I didn't miss nothing and this is not already implemented in some way!

Thanks in advance for your answer and for you work @taylorotwell :)

**Comment by marcusmyers** [comment]
@dib258 You could try (laravel-frontend-presets/tailwindcss)[https://github.com/laravel-frontend-presets/tailwindcss] although I haven't tested on laravel 6.0 yet.

**Comment by Naoray** [comment]
You can use macros to register your own preset

**Comment by driesvints** [comment]
We're planning on adding a TailwindCSS preset later this year. I've opened up an issue for this here: https://github.com/laravel/ui/issues/21

We probably won't be adding other css frameworks out of the box. Feel free to create your own presets as a package.

**Comment by mattfletcher** [comment]
@dib258 By way of an example of a preset as a third-party package, I integrated UIkit as a new preset at https://github.com/Torrix/laravel-ui-uikit

**Comment by Naoray** [comment]
No offense @mattfletcher but you just copied the code of this repo and replaced it with your own Implementation, that s not how it s supposed to work. You should just be able to add your own preset by using the macros on both Commands...

**Comment by mattfletcher** [comment]
@Naoray it would be great if it worked like that, but unfortunately all the blade *.stub file paths are hard-coded into src/AuthCommand.php, rather than somewhere in src/Presets/Bootstrap.php. Therefore all the stubs needed overwriting with UIkit versions, and once that was done, given that laravel/ui is explicitly not accepting new presets, there seemed no point preserving what was left of the bootstrap preset.

**Comment by mattfletcher** [comment]
@Naoray I'm looking at it again with fresh eyes, and I think I've got a better understanding of how the different files work together. I'm going to try and rebuild my version whilst leaving as much of the original package intact as possible. This will make backporting changes from the parent easier, and I guess if the intention of Laravel - not to add new presets - changes in the future, it would make it easier to merge my version in.

**Comment by mattfletcher** [comment]
Thank you @Naoray for your feedback. I've taken it on-board and pushed the changes to GitHub. If you have the time, I'd appreciate you taking another look to let me know if this is more how the package is intended to be extended.

**Comment by Naoray** [comment]
@mattfletcher I don't think you understood what I wanted to say. You can add this package as a dependency of yours and simply use the macros like

```php
class YourServiceProvider extends ServiceProvider
{
    protected method boot()
    {
        UiCommand::macro('your-preset-name', function ($command) {
            // do your thing
        });

       AuthCommand::macro('your-preset-name', function ($command) {
          // do your thing
      });
   }
}
```

Then you can call them with:

```bash
php artisan ui --type=your-preset-name

php artisan ui:auth --type=your-preset-name
```

**Comment by mattfletcher** [comment]
@Naoray oh I see! Yeah that's much simpler. I will have to try that out over the next few days. Thank you for your guidance on this. I'll get there!
