### ISSUE TITLE
Add TailwindCSS preset

### ISSUE THREAD

**Issue by driesvints** [laravel/ui#21]
We're planning on adding a TailwindCSS preset later this year.

Use https://github.com/laravel-frontend-presets/tailwindcss for now.

**Comment by dakira** [comment]
It would be great if one could mix and match. Bootstrap with React, Vue with Tailwind.

**Comment by AndrewFlook** [comment]
Why not offer the ability to pick your preferred CSS and/or JS presets individually of each other.
CSS - Bootstrap, Bulma, Tailwind, or even no CSS framework.
JS - React, Vue, Alpine (& Livewire), or no JS framework.

**Comment by driesvints** [comment]
@AndrewFlook you can add your own presets: https://laravel.com/docs/6.x/frontend#adding-presets

**Comment by princeteck** [comment]
+1 for tailwindcss

**Comment by RahulDey12** [comment]
I am working on this. Hopefully, I will send a pull request within a week. :)

**Comment by taylorotwell** [comment]
Soon.
