### ISSUE TITLE
Riot.js scaffolding support

### ISSUE THREAD

**Issue by GianlucaGuarini** [laravel/ui#24]
Hi there, I am the Riot.js maintainer. Riot.js shares many of the  simplicity core concepts with Laravel and I'd love to create a ui riot setup for it. Would you accept PRs adding Riot.js support to the project?

**Comment by driesvints** [comment]
Heya, I'm very sorry but on this moment we're not accepting more presets.

**Comment by driesvints** [comment]
The UICommand has support for macros though so packages can be made for it. I'll add a note to my todo list to document this.
