### ISSUE TITLE
why views use passwords but route use password

### ISSUE THREAD

**Issue by sinkcup** [laravel/ui#25]
Laravel build-in:

- views path: [passwords/reset](https://github.com/laravel/ui/tree/master/src/Auth/bootstrap-stubs/auth/passwords)
- route name: [password.reset](https://github.com/laravel/framework/blob/v6.0.1/src/Illuminate/Routing/Router.php#L1182)

it means we should use plural in views and singular in route? is there a reason?

**Comment by driesvints** [comment]
Don't think there's a particularly reason. It's been this way for as long as I can remember.
