### ISSUE TITLE
New confirm.stub file not migrated to views directory

### ISSUE THREAD

**Issue by taylormaguire** [laravel/ui#39]
- UI Version: 1.1.0
- Laravel Version: 6.2.0
- PHP Version: 7.3.9
- Database Driver & Version: NA

### Description:
The new confirm.stub file is not copied over when you run "php artisan ui:auth".

It appears to be missing in the line below in AuthCommand.php file for version 1.1.0, it does however appear in the dev-master branch. Packagist appears to be defaulted to 1.1.0 so when you start a new project and do "laravel new blog" and then "composer require laravel/ui" it pulls in the package without the confim.stub file.

```       
 'auth/passwords/confirm.stub' => 'auth/passwords/confirm.blade.php',
```

### Steps To Reproduce:

```
laravel new blog
```
```
composer require laravel/ui
```
```
php artisan ui:auth
```

from here the confirm.blade.php file is missing, and if you look in the vendor files its missing in list of files to copy in AuthCommand.php.

**Comment by driesvints** [comment]
Heya, please see https://github.com/laravel/ui/pull/36
