### ISSUE TITLE
Optionally exclude Bootstrap from JS presets

### ISSUE THREAD

**Issue by jrd-lewis** [laravel/ui#40]
Just wondering, could a flag be added to optionally exclude Bootstrap when scaffolding Vue or React? A use case would be when someone wants to use either JavaScript framework, but plans to use another CSS framework like Bulma or Tailwind instead of Bootstrap. As of 1.1.1, a user would have to manually remove the references to it before compiling.

**Comment by driesvints** [comment]
Yeah we can definitely look into that. Feel free to send in a PR.

**Comment by driesvints** [comment]
Closing as Taylor is working on a new version of the package that'll have major changes to it.
