### ISSUE TITLE
Vue version should be align with vue-template-compiler

### ISSUE THREAD

**Issue by satyakresna** [laravel/ui#43]
- UI Version: 1.1.1
- Laravel Version: 6.5.1

### Description:
I check `vue` version is not align with `vue-template-compiler` after I run `php artisan ui vue`. The vue version is **2.5.17** and vue-template-compiler is **2.6.10**. 

The problem comes when I use `import Vue from 'vue'` and run `npm run watch`. It says cannot find 'vue' module. Here's the detail error message:

```
ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve 'vue' in '/Users/satyakresna/Sandbox/lava/resources/js'
 @ ./resources/js/app.js 1:0-22 3:0-3 19:14-17
 @ multi ./resources/js/app.js
```

I check in `node_modules` folder, vue version **2.5.17** is located in `@vue` folder instead of `vue`. I try to fixed by use `import Vue from '@vue'` but it doesn't solve the problem. Then, I try to update the `vue` version same with the `vue-template-compiler` version which is **2.6.10**. After I update it, I check `vue` is located in `vue` instead of `@vue` folder in `node_modules`. I update syntax again by use `import Vue from 'vue'` and run `npm run watch` and it works like charm.

I googling why vue version must align with vue-template compiler version and find the answer in [Vue loader documentation](https://vue-loader.vuejs.org/guide/#manual-setup):

```
Every time a new version of vue is released, a corresponding version of vue-template-compiler is released together. The compiler's version must be in sync with the base vue package so that vue-loader produces code that is compatible with the runtime. This means every time you upgrade vue in your project, you should upgrade vue-template-compiler to match it as well.
```

### Steps To Reproduce:
1. Install `laravel/ui` package.
2. Install vue scaffolding by run `php artisan ui vue`.
3. Use `import Vue from 'vue'` in `resource/js/app.js` and run `npm run watch` but Vue module not found.
4. I check in `node_modules` that vue is located in `@vue` folder then try to fixed by use `import Vue from '@vue'` but it still Vue module not found.
5. I try to update vue version same with vue-template-compiler which is version **2.6.10**. 
6. After I update it, I check `vue` is located in `vue` instead of `@vue` folder in `node_modules`.
7. I update syntax again by use `import Vue from 'vue'` and run `npm run watch` and it works like charm.

**Comment by driesvints** [comment]
I can install and run everything fine on a fresh Laravel install. I don't get the error at step 3.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by satyakresna** [comment]
Hi @driesvints, thanks for testing. Indeed, you're right. I just run everything on a fresh Laravel install and add vue by using laravel/ui it doesn't get error and include install vue-router and it doesn't get an error too. Hmm. 🤔

I'm sorry, I should triple check for this case. Thank you. 🙏
