### ISSUE TITLE
deps are missing in bootstrap scaffold

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [laravel/ui#50]
- UI Version: v6.9.0
- Laravel Version: v1.1.2
- PHP Version: v7.4
- Database Driver & Version: sqlite3

### Description:
``css-loader`` and ``webpack`` deps arent added in bootstrap scaffold

### Steps To Reproduce:
- ``laravel new myapp``
- install laravel/ui
- ``php artisan ui bootstrap --auth``
- ``npm install && npm run dev``
- observe missing dependency errors

**Comment by driesvints** [comment]
I can run these steps just fine
