### ISSUE TITLE
Support agnostic scaffolding

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [laravel/ui#55]
I suggest supporting an agnostic scaffolding without any preset to permit developers to build their own auth layout. Also, I would suggest to build a better HTML5 structure for each component.

I'm used to separate the login page from login-form and provide all necessary tags like section, fieldset, legend ect..

**Comment by driesvints** [comment]
We have no plans atm to support any other preset than the current ones or planned ones. You can add your own preset if you want: https://laravel.com/docs/6.x/frontend#adding-presets

**Comment by bram1028** [comment]
Look like `artisan ui:controllers` solves this. It would be helpful if this was documented. I found it too late.

**Comment by IAndreaGiuseppe** [comment]
I wrote a package on my on: https://packagist.org/packages/iag/blank-auth

**Comment by driesvints** [comment]
@bram1028 Feel free to send in a pr to the docs

**Comment by benjibee** [comment]
@driesvints, @taylorotwell  I understand being hesitant to add additional presets as it could be nearly impossible to keep up with various frameworks and trends, but having a framework-agnostic preset is the opposite of that.

A quick glance through closed issues (#88, #74, #55) shows this is likely useful to many who don't need to build their own preset but would like to have all the same views scaffolded but without framework-specific classes, wrapper-divs, etc.

If you don't have a personal need for this, perhaps we could get a PR going. I'm guessing @IAndreaGiuseppe might have something useful already!

**Comment by driesvints** [comment]
@benjibee we're currently working on some other solutions and won't be pursuing any further changes to this package.

**Comment by benjibee** [comment]
@driesvints thanks for the update. Any info about these other solutions?

**Comment by driesvints** [comment]
Not atm no
