### ISSUE TITLE
Nuxt preset

### ISSUE THREAD

**Issue by superbiche** [laravel/ui#6]
Could this be the place for a Nuxt.js preset, with a probably much deeper level of integration with routing, auth...

I'm not coming with an out-of-the-box solution, I'd just like to know if we start building it here or on another repo.

Bizous,
Michel

**Comment by driesvints** [comment]
I'm very sorry but we've decided to not add more presets. The UICommand has support for macros though so packages can be made for it. I'll add a note to my todo list to document this.
