### ISSUE TITLE
NPM install gives error cannot find error-stack-parser

### ISSUE THREAD

**Issue by Elshaden** [laravel/ui#63]
- UI Version: #.#.#
- Laravel Version: 6.#.#
- PHP Version: 7.2.#
- Database Driver & Version:

### Description:
in fresh Laravel installation after php artisan ui bootstrap --auth
when npm install I get this error
'''
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-stack-parser
npm ERR! 404
npm ERR! 404  'error-stack-parser@^2.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'friendly-errors-webpack-plugin'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
'''

### Steps To Reproduce:
npm install

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
