### ISSUE TITLE
PhpStorm warns of duplicate class name

### ISSUE THREAD

**Issue by timrspratt** [laravel/ui#67]
- UI Version: 2.x
- Laravel Version: dev-master
- PHP Version: 7.4.3

### Description:

With the refactor of the Auth stubs to the UI package, PhpStorm highlights of duplicate declarations of the class names. Should these .php files be changed to .stub files?

![image](https://user-images.githubusercontent.com/20431294/75626809-96ccab00-5bc2-11ea-86da-0ffdddff6817.png)

**Comment by driesvints** [comment]
I'll try to send in a pr for this later today 👍

**Comment by timrspratt** [comment]
Thanks @driesvints, appreciate it!
