### ISSUE TITLE
Macro system doesn't work properly.

### ISSUE THREAD

**Issue by mathieutu** [laravel/ui#71]
- UI Version: 2.0.1
- Laravel Version: 7.0.4
- PHP Version: 7.4.2

### Description:
Hi,
`$macro` belongs to `\Illuminate\Console\Command` and is shared between all the command. It implies that if you add a macro to `AuthCommand` called `test`, it will override any `test` macro already in `\Illuminate\Console\Command`.

Besides it could be a problem by colliding with other macros directly set in Command, it makes impossible to register an Auth command with the same name than an UI command, and so, it's impossible to have the proper usage: 

```
ui test
ui:auth test
```

One solution could be to implement a macro like method directly in the Ui and Auth Commands (and could be nice to call it `preset`?)

Would be glad to open a PR about that if ok for you.
Thanks,
Matt'

### Steps To Reproduce:
```php
use Laravel\Ui\UiCommand;
use Laravel\Ui\AuthCommand;

AuthCommand::macro('test', function ($command) {
	dump('Auth Command');
});

UiCommand::macro('test', function ($command) {
	dump("UI Command");
});

Artisan::call('ui:auth test'); // Ui Command
Artisan::call('ui test'); // Ui Command

\Illuminate\Console\Command::hasMacro() // true
```

**Comment by driesvints** [comment]
I'm not entirely sure if it's a good idea to share macros like this. These commands have different use cases so I could see unexpected things maybe happening if a wrong command was executed with the same macro name. I'll go over this with Taylor.

**Comment by taylorotwell** [comment]
I don't think you should try to use `laravel/ui` for these presets anymore. Just install them using your own command that copies the files over.

**Comment by mathieutu** [comment]
@taylorotwell Are you saying that laravel/ui can't be extended with other presets anymore ?

Because if this is true, this is quite a breaking change, the doc should be updated, and the package too as it check if there is any macro.

<img width="734" alt="Screenshot 2020-03-06 at 18 08 31" src="https://user-images.githubusercontent.com/11351322/76105622-9030a000-5fd5-11ea-9525-fc753ce404d0.png">
