### ISSUE TITLE
--auth option doesn't work for macro.

### ISSUE THREAD

**Issue by mathieutu** [laravel/ui#72]
- UI Version: 2.0.1
- Laravel Version: 7.0.4
- PHP Version: 7.4.2

### Description:
This issue has nothing in common with #71, but #71 makes this one a bit more difficult to understand, so I've tried to separate both the most.

On these lines:
https://github.com/laravel/ui/blob/948bd6ad08467b8e9cd03cd2af8d86a3a330bbc0/src/UiCommand.php#L36-L48

We can see that if there is a UI macro called `test` it will early return the result of the macro (which is supposed to be void, as we're in a command). So the `--auth` condition will never be reached, and so if a launch `ui test --auth`, the auth part will never be executed.

One solution would be to set the macro or standard preset choice in another function, so early return would not shunt the `--auth` part.

I'd be glad to make the PR if ok for you.

Thanks,
Matt'

### Steps To Reproduce:
```php
use Laravel\Ui\UiCommand;
use Laravel\Ui\AuthCommand;

UICommand::macro('test', function ($command) {
	dump('ui Command');
});

// This should throw a `Invalid preset.` error for the auth part (or launch the auth preset `test` too.
Artisan::call('ui test --auth'); // Ui Command
```

**Comment by driesvints** [comment]
The idea behind the macro is that you completely overwrite with a custom preset. If you call the auth afterwards it'll call the auth command with the bootstrap preset and that might be unwanted for some macros.

**Comment by mathieutu** [comment]
@driesvints Actually the cli help for `php artisan ui` says 
```
Usage:
  ui [options] [--] <type>

Options:
  --auth             Install authentication UI scaffolding
```  
...
without any mention to bootstrap.

I'm also seeing that the doc mention `php artisan ui vue --auth` and `php artisan ui react --auth` but there is no auth preset for vue and react, and that's the boostrap one which is installed. I find really weird that it installs automatically a auth scaffolding for a front framework I don't want.

This is what I had in mind:

```php
public function handle()
    {
        $preset = $this->argument('type');

        $this->executeUIInstallation($preset);

        if ($this->option('auth')) {
            $this->call("ui:auth", ['type' => $preset]);
        }
    }

    protected function executeUIInstallation($preset)
    {
        if (static::hasMacro($preset)) {
            return call_user_func(static::$macros[$preset], $this);
        }  
        
        if (in_array($preset, ['bootstrap', 'vue', 'react'])) {
            return $this->{$preset}();
        }
        
        throw new InvalidArgumentException("Invalid preset $preset.");
    }
```

If this is not supposed to work like that, there is in my opinion a serious misunderstanding of the way of the package should work.

```
// Generate basic scaffolding...
php artisan ui bootstrap
php artisan ui vue
php artisan ui react

// Generate login / registration scaffolding...
php artisan ui bootstrap --auth
php artisan ui vue --auth
php artisan ui react --auth
``` 

Reading this, I would expect to be able to use `php artisan ui tailwindcss` and `php artisan ui tailwindcss --auth` in the same way (and I'm not the only one, as we have the issue in the tailwindcss preset).

I'd be glad to handle all of theses presets issues in a PR if you want to.

Thanks,
Matt'

**Comment by driesvints** [comment]
@mathieutu I doubt we'll be making big changes to the package like this atm since we'll be overhauling the package at some point in the near future. You're always free to attempt a pr to see if taylor would accept it but I doubt it.

**Comment by mathieutu** [comment]
Ok. If you plan to rewrite that, I will not invest more on it for now, and we will just patch the presets.
