### ISSUE TITLE
if i delete sass folder then run artisan ui

### ISSUE THREAD

**Issue by khatabwedaa** [laravel/ui#77]
- UI Version: 2.0
- Laravel Version: 7.1.3
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
if i delete sass folder then run artisan ui get error
```php
 ErrorException 

  copy(/home/khatabwedaa/Dev/laravel/e-commerce/resources/sass/_variables.scss): failed to open stream: No such file or directory
```
laravel ui should create folder if not existing can you add this guys :thinking:

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
