### ISSUE TITLE
route:cache unable to serialize where Auth::routes used with multiple sub-domains

### ISSUE THREAD

**Issue by lightwalkernet** [laravel/ui#85]
- UI Version: v2.0.1
- Laravel Version: v7.3.0
- PHP Version: 7.2.28 
- Database Driver & Version: mysql 5.7.29

### Description:
Error runnning artisan route:cache when using multiple Auth::routes inside sub domains groups
Seems to be caused by named routes being the same.
### Steps To Reproduce:

```
Route::domain('somethingelse.myapp.com')->group(function () {
    Auth::routes();
});

Route::domain('something.myapp.com')->group(function () {
    Auth::routes();
});

```

then run php artisan route:cache gets

```
Unable to prepare route [login] for serialization. Another route has already been assigned name [login].
```

**Comment by driesvints** [comment]
Export your routes and assign them names.
