### ISSUE TITLE
RegisterController stub User Model does not respect auth config

### ISSUE THREAD

**Issue by dhandarbeit-tk** [laravel/ui#89]
- UI Version: 2.0.1
- Laravel Version: 7.4.0

### Description:
The stub for RegisterController (stubs/Auth/RegisterController.stub) has the static line

```
use App\User;
```

Issue: App\User might not be defined.
Proposal: Use config value of 'auth.providers.users.model' instead

**Comment by driesvints** [comment]
Feel free to change this in your own app. You control this file.
