### ISSUE TITLE
Migration not working

### ISSUE THREAD

**Issue by keeloren** [laravel/ui#93]
- UI Version: ^2.0
- Laravel Version: ^7.0
- PHP Version: 7.2
- Database Driver & Version:

### Description:
After i install package, i try "php artisan migrate" but table "password_reset" was not created.

### Steps To Reproduce:
1. Install source base Laravel.
2. Run: php artisan migrate
3. Run: composer require laravel/ui
4. Run: php artisan migrate => nothing to migrate

**Comment by driesvints** [comment]
You need to run the ui command with the auth flag to scaffold the migration: https://laravel.com/docs/7.x/frontend

**Comment by keeloren** [comment]
No, t want to run migration for API, I not using front end.

**Comment by febrihidayan** [comment]
it seems I also experienced the same thing

**Comment by driesvints** [comment]
We've fixed this in the meantime: https://github.com/laravel/laravel/commit/9e5ba571a60a57ca2c3938bc5bd81d222cb6e618

**Comment by febrihidayan** [comment]
@driesvints Thank you for the information

**Comment by sinkcup** [comment]
this file should be delete from laravel ui @driesvints 

> .PHP Fatal error:  Cannot declare class CreatePasswordResetsTable, because the name is already in use in vendor/orchestra/testbench-core/laravel/database/migrations/2014_10_12_100000_create_password_resets_table.php on line 7

https://github.com/laravel/laravel/blob/v7.25.0/database/migrations/2014_10_12_100000_create_password_resets_table.php
https://github.com/laravel/ui/blob/v2.2.0/stubs/migrations/2014_10_12_100000_create_password_resets_table.php

**Comment by driesvints** [comment]
@sinkcup that seems to be testbench related.

**Comment by sinkcup** [comment]
@driesvints I know, but the real reason is: testbench use laravel 7 which has the same migration file as laravel ui.
I delete it manually, it's fine now.
so maybe it should be delete from this project.

**Comment by crynobone** [comment]
@sinkcup No, Laravel UI migration should stay. 

I made a fix to avoid collision for Testbench 6 (for Laravel 8) by prefixing the migration files with `testbench_`. We can backport this to Testbench 5 (Laravel 7).

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-core/commit/99f1b70cb932145006641421258c7a92a2d68be9

Can anyone confirm this fixed the issue, will tagged a patch release once confirmed.

**Comment by driesvints** [comment]
Sweet. Thanks @crynobone!
