### ISSUE TITLE
Prevent from erasing existing HomeController file

### ISSUE THREAD

**Issue by khalyomede** [laravel/ui#94]
## Description

I got my `HomeController.php` file erased after I ran `php artisan ui bootstrap --auth`.

## Reproduce

1. Run `php artisan make:controller HomeController`
2. (optional) customize the content inside
3. Run `php artisan ui bootstrap --auth`
4. The `HomeController` content has been erased

## Expected behavior

The script stops if it has got the `--auth` option and there is an existing `app/Http/Controllers/HomeController.php` file.

## Suggestion

Maybe we could have the same behavior as when we create controllers, e.g. using `--force` it would erase the content anyway, but warn and die if the file exists otherwise?

We could probably check if the file already exists and the `--force` option is not present, like before this line https://github.com/laravel/ui/blob/2.x/src/AuthCommand.php#L64?

**Comment by driesvints** [comment]
I personally consider this an enhancement rather than a bug but I've sent in a quick PR for this: https://github.com/laravel/ui/pull/95
